class Collection4 {
  final String name, author,location, date, width, height,type, description, image;
  Collection4({
    required this.name,
    required this.author,
    required this.location,
    required this.date,
    required this.type,
    required this.description,
    required this.image,
    required this.width,
    required this.height,
  });
}

List<Collection4> collections4 = [
Collection4(
author: "Blake, Robert",
name: "A Figure Bowing before a Seated Old Man with his Arm Outstretched in Benediction. Verso: Indecipherable Sketch",
description: "Presented by Mrs John Richmond 1922",
date: "",
width: "394",
height: "419",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00001_8.jpg",
location: "Tate Modern",
type: "Watercolour, ink, chalk and graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, Robert",
name: "Two Drawings of Frightened Figures, Probably for ‘The Approach of Doom’",
description: "Presented by Mrs John Richmond 1922",
date: "",
width: "311",
height: "213",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00002_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Blake, Robert",
name: "The Preaching of Warning. Verso: An Old Man Enthroned Between Two Groups of Figures, by ?William Blake",
description: "Presented by Mrs John Richmond 1922",
date: "1785",
width: "343",
height: "467",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00003_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, Robert",
name: "Six Drawings of Figures with Outstretched Arms",
description: "Presented by Mrs John Richmond 1922",
date: "",
width: "318",
height: "394",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00004_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Blake, William",
name: "The Circle of the Lustful: Francesca da Rimini (‘The Whirlwind of Lovers’)",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "243",
height: "335",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00005_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Ciampolo the Barrator Tormented by the Devils",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "240",
height: "338",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00006_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Baffled Devils Fighting",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "242",
height: "334",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00007_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Six-Footed Serpent Attacking Agnolo Brunelleschi",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "246",
height: "340",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00008_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Serpent Attacking Buoso Donati",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "241",
height: "335",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00009_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Pit of Disease: The Falsifiers",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "243",
height: "340",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00010_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Dante Striking against Bocca Degli Abati",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1826",
width: "236",
height: "340",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00011_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job and his Family",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1828",
width: "184",
height: "150",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00012_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Satan before the Throne of God",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "197",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00013_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job’s Sons and Daughters Overwhelmed by Satan",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "197",
height: "153",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00014_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper    "
),
Collection4(
author: "Blake, William",
name: "The Messengers tell Job of his Misfortunes",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "200",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00015_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Satan Going Forth from the Presence of the Lord, and Job’s Charity",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00016_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Satan Smiting Job with Sore Boils",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "153",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00017_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job’s Comforters",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "153",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00018_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job’s Despair",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the Art Fund 1919",
date: "1825",
width: "199",
height: "150",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00019_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Vision of Eliphaz",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00020_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job Rebuked by his Friends",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00021_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job’s Evil Dreams",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "197",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00022_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Wrath of Elihu",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "200",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00023_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Lord Answering Job out of the Whirlwind",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00024_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "When the Morning Stars Sang Together",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "191",
height: "150",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00025_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Behemoth and Leviathan",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "200",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00026_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Fall of Satan",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "186",
height: "150",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00027_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "The Vision of Christ",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "200",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00028_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job’s Sacrifice",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "198",
height: "150",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00029_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Every Man also Gave him a Piece of Money",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "197",
height: "150",
image: "",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job and his Daughters",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the the Art Fund 1919",
date: "1825",
width: "199",
height: "151",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00031_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Job and his Family Restored to Prosperity",
description: "Purchased with the assistance of a special grant from the National Gallery and donations from the Art Fund, Lord Duveen and others, and presented through the Art Fund 1919",
date: "1825",
width: "196",
height: "149",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00032_8.jpg",
location: "Tate Modern",
type: "Line engraving on paper"
),
Collection4(
author: "Blake, William",
name: "Sketch for ‘The Four and Twenty Elders Casting their Crowns before the Divine Throne’. Verso: Standing Figure with Arms at his Side",
description: "Presented by Mrs John Richmond 1922",
date: "1803",
width: "488",
height: "389",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00033_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "‘Europe’: Fragment of Pages 3 and 4",
description: "Presented by Mrs John Richmond 1922",
date: "1794",
width: "92",
height: "166",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00034_8.jpg",
location: "Tate Modern",
type: "Relief etching and watercolour on paper"
),
Collection4(
author: "Blake, William",
name: "Songs of Innocence and of Experience: Infant Sorrow",
description: "Presented by Mrs John Richmond 1922",
date: "1794",
width: "112",
height: "97",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00035_8.jpg",
location: "Tate Modern",
type: "Relief etching on paper"
),
Collection4(
author: "Blake, William",
name: "‘Songs of Innocence and of Experience’: ‘Infant Sorrow’",
description: "Presented by Mrs John Richmond 1922",
date: "1794",
width: "112",
height: "97",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00036_8.jpg",
location: "Tate Modern",
type: "Relief etching on paper"
),
Collection4(
author: "Blake, William",
name: "‘Songs of Innocence and of Experience’: ‘Spring’",
description: "Presented by Mrs John Richmond 1922",
date: "1794",
width: "115",
height: "79",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00037_8.jpg",
location: "Tate Modern",
type: "Relief etching on paper"
),
Collection4(
author: "Blake, William",
name: "‘Songs of Innocence’: Title-Page",
description: "Presented by Mrs John Richmond 1922",
date: "1789",
width: "120",
height: "64",
image: "",
location: "Tate Modern",
type: "Relief etching on paper"
),
Collection4(
author: "Blake, William",
name: "‘Songs of Innocence’: Title-Page",
description: "Presented by Mrs John Richmond 1922",
date: "1789",
width: "120",
height: "64",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00039_8.jpg",
location: "Tate Modern",
type: "Relief etching on paper"
),
Collection4(
author: "Blake, William",
name: "Sketch for ‘Tiriel Supporting the Dying Myratana’. Verso: Sketch for ‘Tiriel Supporting the Dying Myratana’",
description: "Presented by Mrs John Richmond 1922",
date: "1786",
width: "291",
height: "450",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00040_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Landscape near Felpham",
description: "Presented by Mrs John Richmond 1922",
date: "1800",
width: "237",
height: "343",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00041_8.jpg",
location: "Tate Modern",
type: "Graphite and watercolour on paper"
),
Collection4(
author: "Blake, William",
name: "Two Figures in a Decorative Border",
description: "Presented by Mrs John Richmond 1922",
date: "1790",
width: "122",
height: "203",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00042_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Preliminary Sketch for ‘Christ Girding Himself with Strength’. Verso: Standing Figure with One Arm Raised",
description: "Presented by Mrs John Richmond 1922",
date: "1805",
width: "505",
height: "425",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00043_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Lower Half of a Woman Playing a Harp. Verso: Seraphim and Other Drawings",
description: "Presented by Mrs John Richmond 1922",
date: "1785",
width: "268",
height: "450",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00044_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "St Christopher, Copy from an Engraving? Verso:Part of a Face: Copy from a Plaster Cast: a Daughter of Niobe?",
description: "Presented by Mrs John Richmond 1922",
date: "1779",
width: "435",
height: "338",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00045_8.jpg",
location: "Tate Modern",
type: "Ink on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "The Crucifixion",
description: "Presented by Mrs John Richmond 1922",
date: "1825",
width: "432",
height: "276",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00046_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Composition Sketch, Possibly a Subject from Dante. Verso: A Man Standing over a Figure Reclining on a Bed",
description: "Presented by Mrs John Richmond 1922",
date: "1800",
width: "454",
height: "339",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00047_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Composition Sketch. Verso: Standing Figure Holding a Spear",
description: "Presented by Mrs John Richmond 1922",
date: "1805",
width: "508",
height: "370",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00048_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Blake, William",
name: "Composition Sketch for ‘The Fall of the Rebel Angels’? Verso: Standing Figure with Flaming Hair",
description: "Presented by Mrs John Richmond 1922",
date: "1805",
width: "502",
height: "425",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00049_8.jpg",
location: "Tate Modern",
type: "Graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Richmond, George",
name: "Tracing of Title-Page of Blake’s ‘Book of Job’",
description: "Presented by Mrs John Richmond 1922",
date: "1826",
width: "214",
height: "157",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00050_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "British School 18th century",
name: "[title not known]",
description: "Bequeathed by Miss Julia Emily Gordon 1896",
date: "",
width: "",
height: "",
image: "",
location: "Tate Modern",
type: "Watercolour on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Woman’s Head",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1870",
width: "203",
height: "184",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00057_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Sleeping Woman’s Head, possibly for ‘The Rose Bower’ in the ‘Briar Rose’ Series",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1871",
width: "274",
height: "222",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00058_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Man’s Head",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1866",
width: "222",
height: "171",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00059_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Girl’s Head",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1866",
width: "260",
height: "216",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00060_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Standing Woman for ‘The Passing of Venus’",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1877",
width: "269",
height: "179",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00061_8.jpg",
location: "Tate Modern",
type: "Graphite and watercolour on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Seated Woman for ‘The Passing of Venus’",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1877",
width: "261",
height: "225",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00062_8.jpg",
location: "Tate Modern",
type: "Graphite and watercolour on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of Seated Figure for ‘The Garden Court’ in the ‘Briar Rose’ Series",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1873",
width: "126",
height: "180",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00063_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of Seated Figure for ‘The Garden Court’ in the ‘Briar Rose’ Series",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1873",
width: "126",
height: "179",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00064_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Figure Study for ‘The Rose Bower’ (Briar Rose Series). Verso: Study of the Head of Merlin for ‘The Beguiling of Merlin’",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1872",
width: "212",
height: "235",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00065_8.jpg",
location: "Tate Modern",
type: "Charcoal and graphite on paper. Verso: graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Three Studies for ‘The Beguiling of Merlin’",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "1872",
width: "323",
height: "222",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00066_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Studies of a Sleeve",
description: "Bequeathed by A.N. MacNicholl 1916",
date: "",
width: "244",
height: "152",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00067_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Kneeling Woman",
description: "Presented by Lord Duveen 1924",
date: "",
width: "152",
height: "165",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00068_8.jpg",
location: "Tate Modern",
type: "Chalk on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Stooping Woman",
description: "Presented by Lord Duveen 1924",
date: "",
width: "152",
height: "165",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00069_8.jpg",
location: "Tate Modern",
type: "Chalk on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of a Female Head for ‘The Hours’",
description: "Presented by Lord Duveen 1925",
date: "1872",
width: "146",
height: "149",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00070_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Female Head",
description: "Presented by Lord Duveen 1925",
date: "",
width: "146",
height: "149",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00071_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Ruth and Boaz",
description: "Bequeathed by J.R. Holliday 1927",
date: "1879",
width: "645",
height: "518",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00072_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "The Finding of Moses",
description: "Bequeathed by J.R. Holliday 1927",
date: "1879",
width: "647",
height: "518",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00073_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "St Alban",
description: "Bequeathed by J.R. Holliday 1927",
date: "1875",
width: "730",
height: "398",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00074_8.jpg",
location: "Tate Modern",
type: "Charcoal and graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "St Aidan",
description: "Bequeathed by J.R. Holliday 1927",
date: "1875",
width: "730",
height: "400",
image: "",
location: "Tate Modern",
type: "Charcoal and graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "St Oswald",
description: "Bequeathed by J.R. Holliday 1927",
date: "1875",
width: "730",
height: "400",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00076_8.jpg",
location: "Tate Modern",
type: "Charcoal and graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "St Boniface",
description: "Bequeathed by J.R. Holliday 1927",
date: "1875",
width: "731",
height: "400",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00077_8.jpg",
location: "Tate Modern",
type: "Charcoal and graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Study of the Head of Tristram for ‘The Madness of Sir Tristram’",
description: "Bequeathed by J.R. Holliday 1927",
date: "1862",
width: "101",
height: "131",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00078_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Two Studies of Tristram for ‘The Madness of Sir Tristram’",
description: "Bequeathed by J.R. Holliday 1927",
date: "1862",
width: "207",
height: "241",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00079_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
Collection4(
author: "Burne-Jones, Sir Edward Coley, Bt",
name: "Roundel with the Head of a Warrior",
description: "Bequeathed by J.R. Holliday 1927",
date: "1870",
width: "",
height: "",
image: "http://www.tate.org.uk/art/images/work/A/A00/A00080_8.jpg",
location: "Tate Modern",
type: "Graphite on paper"
),
];