class Collection2 {
  final String name, author,location, date, type, description, image;
  Collection2({
    required this.name,
    required this.author,
    required this.location,
    required this.date,
    required this.type,
    required this.description,
    required this.image,
  });
}

List<Collection2> collections2 = [
  Collection2(
    name: "H Beard Print",
    author: "Laroche(M.)",
    location: "V & A museum",
    type: "Drawing",
    date: "19th century",
    image: "https://framemark.vam.ac.uk/collections/2011FB3700/full/1400,/0/default.jpg",
    description: "Drawing depicting Charles Kean in the character of Leontes in The Winter's Tale.",
  ),
  Collection2(
    name: "Harry Beard Print",
    author: "Leech, John",
    location: "V & A museum",
    type: "Drawing",
    date: "1807-1864",
    image: "https://framemark.vam.ac.uk/collections/2010EJ4097/full/1400,/0/default.jpg",
    description: "Drawing portraying a satirical scene from the opera, Harry Beard Collection.",
  ),
  Collection2(
    name: "Portrait of Frances Anne Vane",
    author: "Dubois-Drahonet, Alexandre-Jean",
    location: "V & A museum",
    type: "Oil Painting",
    date: "1831",
    image: "https://framemark.vam.ac.uk/collections/2015HP7803/full/1400,/0/default.jpg",
    description: "This portrait was painted to commemorate the attendance of Frances Anne, Marchioness of Londonderry at the coronation of William IV in Westminster Abbey in 1831. She is wearing many of her celebrated collection of jewels, partly inherited, partly bought from the wealth of her coalmines, and partly the gift of Tsar Alexander I. Frances Anne was one of the most celebrated society hostesses of her day. Following the death of her husband, Charles William Vane, 3rd Marquess of Londonderry, she took control of their coalmining interests and established herself as formidable business woman.",
  ),
  Collection2(
    name: "Print",
    author: "Walter Hoyle",
    location: "V & A museum",
    type: "Drawing",
    date: "19th century",
    image: "https://framemark.vam.ac.uk/collections/2011EX0530/full/1400,/0/default.jpg",
    description: "Monotype drawing by Walter Hoyle: Great Bardfield Mill",
  ),
  Collection2(
    name: "Landscape",
    author: "Walter Hoyle",
    location: "V & A museum",
    type: "Oil Painting",
    date: "1956",
    image: "https://framemark.vam.ac.uk/collections/2007BP2111/full/1400,/0/default.jpg",
    description: "A mural painting commissioned for the Centre for Cancer Treatment, Mount Vernon Hospital, Northwood, Middlesex. The painting depicts a table laid for breakfast, in the foreground, with a view of a coastal landscape and doves in a tree.",
  ),
  Collection2(
    name: "Miniature Portrait in Case",
    author: "Martin, Abraham",
    location: "V & A museum",
    type: "Drawing",
    date: "about 1680",
    image: "https://framemark.vam.ac.uk/collections/2006BJ4160/full/1400,/0/default.jpg",
    description: "This gold miniature frame contains a portrait in oils on copper of an unidentified man. It has a suspension ring so that it could be worn on a ribbon. The frame is finely engraved with birds, snails, butterflies, flowers and foliage, which stand out from a heavily matted background. The matting was executed by striking a punch with a ring-shaped end repeatedly into the metal. The engraving has been attributed to Abraham Martin because it has some similarity to a watchcase signed by him and made in 1683 for a watch by Thomas Tompion held in the Ashmolean Museum, Oxford.",
  ),

  Collection2(
    name: "Festoon with Fruit, Corn, Nuts and Flowers",
    author: "Gallis, Pieter",
    location: "V & A museum",
    type: "Flask",
    date: "3rd century-4th century",
    image: "https://framemark.vam.ac.uk/collections/2017JW5755/full/!100,100/0/default.jpg",
    description:"",
  ),
  Collection2(
    name: "Akbar",
    author: "Tulsi,Bandi, Madhav",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3744/full/1400,/0/default.jpg",
    description:"In this illustration to the Akbarnama, the official history of the reign of the Mughal emperor Akbar, the ruler is depicted dressed in white in the upper section of the painting. He directs the construction of the royal city of Fathpur ('City of Victory', later known as Fatehpur Sikri) in 1571.",
  ),

  Collection2(
    name: "Akbar",
    author: "Basawan, Nand",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3695/full/1400,/0/default.jpg",
    description:"This painting from the Akbarnama (Book of Akbar) depicts an incident from the life of the Mughal emperor Akbar (r. 1556-1605). Akbar had vowed that if he should be blessed with a son, he would walk to the shrine of the founder of the Chishti order, Shaikh Mu'in ad-Din Chishti, at Ajmer to offer his prayers. He left Agra in January 1570, and swiftly covered the 370 or so kilometers. He is depicted here accompanied by servants carrying emblems of royalty. Abu’l Fazl, in the A’in-i Akbari, the third volume of his history of the reign entitled the Akbarnama, notes that whenever the emperor went out in a formal context, five standards would be carried next to him, as well as the qur, a collection of flags and other insignia. These were all wrapped in red cloth, the colour of royalty. The aftabgir, a shade held over the emperor’s head and seen here, was also on Abu’l Fazl’s list of royal emblems. While in Ajmer, Akbar distributed alms at the shrine, visited other local sacred places, and ordered the construction of new mosques. When a second son, Murad, was born at Sikri some months later to another wife, Akbar returned to Ajmer and had the fort enlarged, new mansions built and gardens laid out for the elite of the court. From then until 1579 he made annual pilgrimages to the city. The composition (tarh) of the painting was designed by Basawan, and the work ('amal), or painting, was done by Nand Gwaliari. [Akbarnama, English translation: Beveridge, vol. II, pp. 510-11]",
  ),
  Collection2(
    name: "Akbar and Hamid Bakari",
    author: "Miskina, Sarwan",
    location: "V & A museum",
    type: "Paiting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3700/full/1400,/0/default.jpg",
    description:"This illustration to the Akbarnama (Book of Akbar) is the right side of a double-page composition (see Museum no. IS.2:56-1896 for the left side). The entire composition depicts a ceremonial hunt that took place near Lahore, in present-day north-east Pakistan, in 1567. The Mughal emperor Akbar (r.1556–1605) is shown in the centre of the painting mounted on horseback with his sword raised. At top right Hamid Bakkari is shown being punished for firing an arrow at one of the servants of the court by having his head shaved and being forced to ride backwards on an ass. The composition was designed by the Mughal court artist Miskina, who also painted the face of the emperor, and the rest was painted by Sarwan.",
  ),
  Collection2(
    name: "Akbar",
    author: "Tulsi, Narayan",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX4155/full/1400,/0/default.jpg",
    description:"This painting from the Akbarnama (Book of Akbar) depicts the Mughal emperor Akbar (r.1556–1605) travelling from Delhi to Agra by boat. Akbar is shown standing up within a royal box inside the boat. Several other boats carrying his entourage can also be seen in the painting. The Mughal court artist Tulsi designed the composition, and Narayan painted the details.",
  ),
  Collection2(
    name: "Khan-i Kilan",
    author: "Miskina, Sarwan",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
      image: "https://framemark.vam.ac.uk/collections/2009BX3741/full/1400,/0/default.jpg",
      description:"This painting from the Akbarnama depicts the wounding of Khan-i Kilan by a Rajput during his march to Gujarat and is by Miskina (whose name is also written as Miskin in the Akbarnama) and Sarwan. The incident took place in 1572 as the Mughal army moved west in a major campaign against the sultanate of Gujarat. On the way, envoys of the chief of Sirohi were received by the Mughal general, Khan-i Kalan. As they were about to depart, one of them suddenly lunged forward and stabbed the general. In retaliation, Khan-i Kalan's companions immediately killed the attacker and others who were with him. The incident made Akbar decide to take personal command of a force to crush the rebellion in Sirohi."
  ),
  Collection2(
    name: "Akbar and Asaf Khan",
    author: "Miskina, Bhagwan",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3697/full/1400,/0/default.jpg",
    description:"This is the left side of a double-page composition from the Akbarnama (Book of Akbar) (the right half is Museum no. IS.2:51-1896). The overall composition was designed by Miskina, one of the greatest artists of the Mughal court, with the details on this half being painted by Bhagwan. Together, they depict the Mughal emperor Akbar (r.1556–1605) receiving spoils of war from his leading general Asaf Khan in Jaunpur in 1565. Akbar’s encampment is shown outside the walls of a fort on a river bank. The text specifies that Asaf Khan brought the rarities of the region for the emperor, and presented him with elephants, and fine horses from Iran and Turkey. These animals are depicted on the other side of the composition (IS.2:51-1896).",
  ),
  Collection2(
    name: "Painting",
    author: "Miskina, Bhura",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3692/full/1400,/0/default.jpg",
    description:"This painting is an illustration from the Akbarnama depicts the Mughal army led by the emperor Akbar, besieging Rai Surjan Hada's fort of Ranthambhor in Rajasthan, in 1569.",
  ),
  Collection2(
    name: "Akbar",
    author: "Kesav Kalan, Chatarmuni",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3709/full/1400,/0/default.jpg",
    description:"This painting by Kesav Kalan and Chetarmuni depicts the emperor Akbar watching an extraordinary display of skill in catching fish from the banks of the river in front of a walled city and is an illustration to the Akbarnama (Book of Akbar).",
  ),
  Collection2(
    name: "Shah Abu'l Ma'ali",
    author: "Jagan, Asir",
    location: "V & A museum",
    type: "Painting",
    date: "1590-95",
    image: "https://framemark.vam.ac.uk/collections/2009BX3665/full/1400,/0/default.jpg",
    description:"This painting designed by the Mughal court artist Jagan, and painted by Asir, is an illustration to the Akbarnama (Book of Akbar), commissioned in 1589 by the emperor Akbar (r.1556–1605) as the official chronicle of his reign. It depicts the execution of Shah Abul Ma’ali at Kabul, in present-day Afghanistan, in 1564.",
  ),
  Collection2(
    name: "Krishna painting Radha",
    author: "Keyt,George",
    location: "V & A museum",
    type: "Painting",
    date: "1948",
    image: "https://framemark.vam.ac.uk/collections/2006AM2326/full/1400,/0/default.jpg",
    description:"The painting depicts Krishna painting the figure of Radha. The two divine Hindu subjects, who represent the archetypal symbol of transcendental love, are here depicted in a manner that reflects the influences of cubism as well as the Kalighat art of Calcutta. The influence of Kalighat art can be seen in the minimal use of lines, large eyes and the curves of the bodies, whereas that of cubism can be detected in the quasi-abstract and angular figure of Krishna. In this painting, we can thus see how Keyt has adopted Western elements into his visual vocabulary to depict a hugely popular theme of Hindu mythology.",
  ),
  Collection2(
    name: "Dancing Lady",
    author: "Roy, Jamini",
    location: "V & A museum",
    type: "Painting",
    date: "1945",
    image: "https://framemark.vam.ac.uk/collections/2013GT2592/full/1400,/0/default.jpg",
    description:"Jamini Roy (1887-1972) was one of the most important artists of the modern period in India, drawing on the popular and folk traditions of rural Bengal for his inspiration. He developed his own personal style which was characterised by bold lines and flat use of colour. He used indigenous materials, including lamp black for the outline drawing, 7 basic colours (Indian red, yellow ochre, cadmium green, vermilion, grey, blue and white), which he applied with organic tempera, earth and mineral pigments to homemade canvas spun with fabric. His paintings can be divided into three main themes: the everyday life of rural Bengal, particularly the women of the aboriginal Santhal community, Hindu mythological subjects and Christian imagery.",
  ),
  Collection2(
    name: "Flower Painting",
    author: "Barwell, Frederick Bacon",
    location: "V & A museum",
    type: "Oil Painting",
    date: "1868",
    image: "https://framemark.vam.ac.uk/collections/2010EE6128/full/1400,/0/default.jpg",
    description:"Seven female figures depicted outside painting centrally placed lilies tree. Signed 'Barwell' and dated '1868' in bottom right corner.",
  ),
  Collection2(
    name: "An Allegory of Painting",
    author: "Reni, Guido",
    location: "V & A museum",
    type: "Oil Painting",
    date: "17th century",
    image: "https://framemark.vam.ac.uk/collections/2007BN6090/full/1400,/0/default.jpg",
    description:"A personification of Painting gestures towards the colour palette in her left hand while cupid, his arrows tossed aside, places a laurel wreath atop her head. This work recalls paintings by the followers of the Bolognese artist Guido Reni (1575 -1642) in style, colour palette and subject matter. Reni was one of the greatest and most influential of the 17th-century Italian painters, whose sophisticated and complex art dominated the Bolognese school. A classicizing artist, deeply influenced by Greco-Roman art and by Raphael but also by the mannered elegance of Parmigianino’s paintings, he sought an ideal beauty. In his religious art he was concerned with the expression of intense emotion, according to his biographer Malvasia, he boasted that he ‘could paint heads with their eyes uplifted a hundred different ways’ to give form to a state of ecstasy or divine inspiration. He was a subtle yet bold colourist, moving from the brilliant colour of his early paintings to the light tonalities and cool, silvery palette of his later work. 1380-1869 recalls Reni followers, Giovan Battista Bolgonini (1611/12-1688) and Giovanni Giacomo Sementi (1583-1636/42) and their works directly after compositions by the Master in particular. The figure of 'Painting' in the V&A picture for example shares the same short nose, large almond eyes, elaborate hairdress, pearl earing and upturned head as the female figure in Sementi's version (Matthiesen and Newhouse Galleries, New York) of Reni's Joseph and Potiphar's Wife now in the Getty Museum. The V&A allegory also recalls Sementi's version (Bolgona, Collection of the Casa di Risparmio) of Reni's Allegory of Drawing and Painting now in the Louvre, Paris. Both have a blonder, 'flatter' appearance than works by the Master and a similar way of painting 'boneless' hands. The subject of Reni's painting implies that Drawing (or Design Disegno) personified by a youth and Painting, embodied by a beautiful young woman, are united, like lovers, in creating harmonious works of art. Analagoulsy, in the V&A picture it appears that cupid, or Love personified, is the inspiration for Painting, and his gesture of placing the laurel crown atop her head suggests a reward for accomplishment in the arts and for victory in love. The notion that love was the ultimate source of inspiration for artists is a topos found throughout Italian artistic treatises of this period. The painting is perhaps also an allusion to Virgil's famous proclamation Omnia vincit amor or 'Love conquers all' (Eclogues 10:69) which was given visual expression by cupid standing triumphant in the midst of various symbolic objects including a laurel wreath or branch to represent learning and the arts. Equally, the crowning of Painting by a winged putto occurs in paintings celebrating the admission of Painting to the Liberal Arts as in Hans van Aachen's work on the subject now in a private collection in Brussels.",
  ),
  Collection2(
    name: "Bandley Hill Adventure Playground",
    author: "Donne Buck",
    location: "V & A museum",
    type: "Painting",
    date: "1968-1969",
    image: "https://framemark.vam.ac.uk/collections/2015HR2759/full/1400,/0/default.jpg",
    description:"Donne Buck was a play worker and campaigner who started his career in the Adventure Playgrounds of London before 1960. By the end of the 1960s, he had moved to Stevenage to oversee play provision in the estates of the New Town. He made this painting of Bandley Hill Adventure Playground after the children had built a large wooden play structure using found and donated materials.",
  ),
];